### ISSUE TITLE
ipv6 leak protection

### ISSUE THREAD

**Issue by emk2203** [tkalfigo/piavpn#1]
Maybe I missed it, but does your script have ipv6 leak protection = shuts down ipv6 before VPN starts and restarts it again after VPN is stopped?

I didn't see a `sh -c 'echo 0 > /proc/sys/net/ipv6/conf/wlan0/disable_ipv6'` in the shutdown script, so I assume it's missing.

**Comment by tkalfigo** [comment]
Nope, you are right. It doesn't. I'm open to PRs if you feel like adding it.

**Comment by emk2203** [comment]
This is not worthy for a PR. It's just adding `sh -c 'echo 1 > /proc/sys/net/ipv6/conf/wlan0/disable_ipv6'` before the VPN is started, and re-enabling it in the shutdown script with `sh -c 'echo 0 > /proc/sys/net/ipv6/conf/wlan0/disable_ipv6'`.

PIA is IPv4 only; the above mentioned lines shut off IPv6 completely as long as PIA is active, the exact same functionality as in the MSWindows application if you enable 'IPv6 leak protection'.

**Comment by tkalfigo** [comment]
Thanks. Fixed as requested.
