### ISSUE TITLE
I have no PIA file in /etc/NetworkManager/system-connections/

### ISSUE THREAD

**Issue by VancouverJohn** [tkalfigo/piavpn#2]
Running Ubuntu 16.04, when I try to use the scripts they point out there is no PIA file in /etc/NetworkManager/system-connections.  Why is this, does it have to do with systemd or something?

**Comment by tkalfigo** [comment]
From the README, under the `Prerequisites` paragraph: 

   ...For details on what to do to enable each region so it is managable with the piavpn.sh script, please read: https://askubuntu.com/questions/57339/connect-disconnect-from-vpn-from-the-command-line/57409#57409?newreg=21c40769970a48909e8fee3df7bb308f

**Comment by tkalfigo** [comment]
Closing as it's related to Ubuntu setup and not current project.
